### ISSUE TITLE
Sync to Three.js r73 version of OrbitController

### ISSUE THREAD

**Issue by bsergean** [mattdesl/three-orbit-controls#11]
Here's the latest version -> 
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/OrbitControls.js

Here's the history. There is now an OrbitConstraint class, which OrbitControls derives from.
https://github.com/mrdoob/three.js/commits/master/examples/js/controls/OrbitControls.js

**Comment by mattdesl** [comment]
Yeah it seems like a bit of refactoring here is needed. :+1: 

I added you as a collaborator to this module. Let me know if you have an npm account for publishing. :smile:

**Comment by bsergean** [comment]
Cool ! I just created an npm account; my user name is bsergean
- Benjamin

**Comment by bsergean** [comment]
Created a pull request for this (github already knows about it, not sure why I'm commenting here ...).

**Comment by mattdesl** [comment]
Should be good now, I think we can close. Added you to npm module, too.

**Comment by bsergean** [comment]
Thanks for adding me to the npm module.
- Benjamin
