### ISSUE TITLE
Uncaught TypeError: (intermediate value).setFromUnitVectors is not a function

### ISSUE THREAD

**Issue by Coilz** [mattdesl/three-orbit-controls#13]
I'm using https://www.npmjs.com/package/three.js version 0.73.0 together with https://www.npmjs.com/package/three-orbit-controls version 72.0.0

The error happens in the OrbitConstraint.update function:

function OrbitConstraint ( object ) {
...
this.update = function() {
...
var quat = new THREE.Quaternion().setFromUnitVectors( object.up, new THREE.Vector3( 0, 1, 0 ) );
...

**Comment by Coilz** [comment]
I'm sorry, I seem to be using r61... :(

**Comment by bsergean** [comment]
So everything's fine right ? Looks like you figured it out on your own.
