### ISSUE TITLE
Why ask user to pass in three instead of requiring as a dependency?

### ISSUE THREAD

**Issue by AndrewRayCode** [mattdesl/three-orbit-controls#15]
I'm making a similar package for the threejs extras subdivision modifier. Why require three to be passed in instead of just requiring it in the library?

**Comment by mattdesl** [comment]
There is a high chance you will end up with duplicate versions of ThreeJS in your final bundle if this module (and a bunch of others) start to `require('three')` directly. Also, there are varying ways of getting ThreeJS into a bundle; some people use browserify-shim, some just add it as a script tag before the Browserify/Webpack bundle, and there are different npm modules that you might choose. The version sometimes depends on the project (some people are still using r69) and ideally this module should just work across as many versions as it can.

By letting the user pass in THREE, it means they don't need to have it defined as a global, and they can choose how to depend on it.

Another approach I've been using recently (see [three-bmfont-text](https://github.com/Jam3/three-bmfont-text)) is just to assume it exists as a global. This is a bit easier for the end-user, but in some cases it can lead to issues – you need to make sure that `THREE` exists as a global before you `require()` the module.

**Comment by AndrewRayCode** [comment]
Cool, thanks for the explanation. I would imagine that if someone is using the npm package, they're using  a modern build tool. The strategy i'm going to go with for now is putting `three` in peerDependencies, which is how other projects treat cases like this, such as [React redux's dependence on React](https://github.com/rackt/react-redux/blob/master/package.json#L75).

I would encourage you not to rely on the global THREE object. That's kind of why we have to manually create these packages in the first place - because the three source relies entirely on global variables and has no dependency system. Also relying on a global is known to cause issues, including as you said changing the order you can require/import things. It also removes the code from the dependency graph, meaning build tools / compilers / code splitters won't be able to do their job properly.
