### ISSUE TITLE
instanceof fails for camera.

### ISSUE THREAD

**Issue by otoomey** [mattdesl/three-orbit-controls#22]
Because you have bundled a copy of Three.js library in your project, `instanceof` fails when I pass a camera I made from another copy of Three.js (that I installed using npm and loaded with typings). Please consider requiring the installation of three.js separately from your orbital-controls package, and then using that one instead.

Or, a quick and non-breaking option would be to change the lines similar to the following:
`if (this.object instanceof THREE.PerspectiveCamera) { ... `
to
`if (this.object.type === "PerspectiveCamera") { ...`

'Orbiting' works without the fix, but zoom and pan are both broken with the following message (I'm just showing the zoom one here):
`WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.`

In case there is confusion, here is a tree of what is happening:

- node_modules
  - @types
      - three (definition file. points to the following three library)
  - three
      - three (standard npm library, the one that I use throughout my project)
  - three-orbitcontrols-ts (your library)
      - three (the same three library, but you have bundled ANOTHER copy just for your module)
      - dist (your orbiting controls code)

**Comment by otoomey** [comment]
sorry wrong repository, meant to put on the ts version

**Comment by theblang** [comment]
https://github.com/nicolaspanel/three-orbitcontrols-ts/issues/1
