### ISSUE TITLE
Zooming in & out of objects in firefox does also scroll the whole page

### ISSUE THREAD

**Issue by bsergean** [mattdesl/three-orbit-controls#6]
Someone fixed this problem in the latest three.js branch, I'm wondering if this fix could be added to three-orbit-controls.

https://github.com/mrdoob/three.js/pull/7310

BTW the fix should be firefox specific to me, because it doesn't sound like it will work with other browsers ... the fix uses this event to handle zooms: https://developer.mozilla.org/en-US/docs/Web/Events/MozMousePixelScroll

**Comment by bsergean** [comment]
Nevermind it looks like the event used prior to this change was already firefox specific; please ignore my comment.

**Comment by mattdesl** [comment]
Hmm so this is still an issue correct?

We can bring in the new code from ThreeJS and make a major bump to whatever the latest ThreeJS version is.

**Comment by bsergean** [comment]
Yes it's still an issue, and the fix won't break other browsers like I thought.

That fix is in the "dev" branch of three.js, which will become r73 of three.js at some point. The r72 version of three.js was just "cut" recently.

**Comment by mattdesl** [comment]
pushed to 71.1.0 thanks for the PR
