### ISSUE TITLE
combination select + three-orbit-controls

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [mattdesl/three-orbit-controls#8]
Seems like I can't use a simple HTML select element anymore when I use three-orbit-controls on a project where my whole viewport is a canvas element.

Any ideas how I could fix this?

**Comment by mattdesl** [comment]
Can you provide a simple example? Did this start happening recently?

It could be that you just need to specify the canvas as the element into the OrbitControls constructor, rather than undefined (which defaults to document.body).

**Comment by geoffreydhuyvetters** [comment]
passing the canvas element works perfectly, thanks for the quick reply :)
